In [1]:
import pandas as pd

In [38]:
#visualizing data
ecommerce = pd.read_csv('Ecommerce_DBS.csv')

display(ecommerce.head(5))
display(ecommerce.info())
display(ecommerce.describe())

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,NPS,Customer Age,Gender,Source,Country,State,Latitude,Longituide
0,46251,08/09/2020,Electronics,12,3,740,7,20,Male,Instagram Campign,Canada,Alberta,55.000000,-115.000000
1,46251,05/03/2022,Home,468,4,2739,8,20,Male,Instagram Campign,Canada,Ontario,50.000000,-85.000000
2,46251,23/05/2022,Home,288,2,3196,10,20,Male,SEM,United States,New Mexico,34.840515,-106.248482
3,46251,12/11/2020,Clothing,196,1,3509,3,20,Male,Instagram Campign,Canada,Saskatchewan,55.000000,-106.000000
4,13593,27/11/2020,Home,449,1,3452,3,20,Female,Instagram Campign,United States,California,36.116203,-119.681564

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  object
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   NPS                    250000 non-null  int64
 7   Customer Age           250000 non-null  int64
 8   Gender                 250000 non-null  object
 9   Source                 250000 non-null  object
 10  Country                250000 non-null  object
 11  State                  250000 non-null  object
 12  Latitude               250000 non-null  float64
 13  Longituide             250000 non-null  float64
dtypes: float64(2), int64(6), object(6)
memory usage: 26.7+ MB

None

,Customer ID,Product Price,Quantity,Total Purchase Amount,NPS,Customer Age,Latitude,Longituide
count,250000.00000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,25004.03624,254.659512,2.998896,2725.370732,4.991832,43.759228,42.400790,-81.648522
std,14428.27959,141.568577,1.414694,1442.933565,3.166732,15.392075,7.214608,37.339110
min,1.00000,10.000000,1.000000,100.000000,0.000000,18.000000,31.169546,-127.647621
25%,12497.75000,132.000000,2.000000,1477.000000,2.000000,30.000000,36.116203,-106.000000
50%,25018.00000,255.000000,3.000000,2724.000000,5.000000,44.000000,42.165726,-74.948051
75%,37506.00000,377.000000,4.000000,3974.000000,8.000000,57.000000,46.250000,-74.948051
max,50000.00000,500.000000,5.000000,5350.000000,10.000000,70.000000,56.415211,98.739075

In [40]:
#data treatments

ecommerce.columns = ecommerce.columns.str.lower()
ecommerce.columns = ecommerce.columns.str.replace(' ', '_')
ecommerce['purchase_date'] = pd.to_datetime(ecommerce['purchase_date'], format='%d/%m/%Y')